title: Gabriel Valenzuela # your name (or website title) here
logo: "/images/Headshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h2>About</h2>
  Future graduate of Master's Program of Data Science at Bellevue Unviersity with a combination of business, computer science, and data science skillsets. Bachelor's Degree in Computer Science with an emphasis in Information Systems from the Unviersity of Wisconsin-Platteville. 
  <br><br>
  <h2>Experience</h2>
  <h3>Unviersity of Wisconsin-Platteville - Office of Institutional Research</h3>
  <h4>Research Intern</h4>
  Developed interactive Fact Book utilizing Microsoft SharePoint and Power BI as well as PeopleSoft Business Intelligence 
  <br>
  <h3>Unviersity of Wisconsin-Platteville - Event Productions</h3>
  <h4>Software Intern</h4>
  Designed documentation system of audio and visual systems used throughout unviersity for future updates
  <br>
  <h3>Discovery Communications - Education Division</h3>
  <h4>Intern</h4>
  Assited in creation of drillthrough reports and quality insurance of online text books used by school districts across the world.
  <br><br>
  <h2>Important Links</h2>
  <br>
  <a href="https://www.linkedin.com/in/gabriel-valenzuela-20152019/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
