title: Gabriel Valenzuela # your name (or website title) here
logo: "/images/Headshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Future Data Science graduate with the combination of business, computer science, and data science skillset. Bachelor's Degree in Computer Science with an emphasis in Information Systems from the Unviersity of Wisconsin-Platteville. 
  <br><br>
  Experience in data visualizations and analysis as a Research Intern within the Office of Insitutional Research at my alma mater. 
  <br><br>
  <a href="https://www.linkedin.com/in/gabriel-valenzuela-20152019/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
