title: Gabriel Valenzuela # your name (or website title) here
logo: "/images/Headshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h4>About</h4>
  Future graduate of Master's Program of Data Science at Bellevue Unviersity with a combination of business, computer science, and data science skillsets. Bachelor's Degree in Computer Science with an emphasis in Information Systems from the Unviersity of Wisconsin-Platteville. 
  <br><br>
  <h4>Experience</h4>
  Unviersity of Wisconsin-Platteville - Office of Institutional Research
  <br>
  Unviersity of Wisconsin-Platteville - Event Productions
  <br>
  Discovery Communications - Education Division
  <br>
  <a href="https://www.linkedin.com/in/gabriel-valenzuela-20152019/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
